package org.isw2.factory;

public enum ControllerType {
    FILE_IS_TOUCHED_BY,
    MERGE_VERSION_AND_COMMIT,
    GET_COMMIT_FROM_GIT,
    GET_FILE_DIFF_BETWEEN_COMMITS,
    GIT_CONTROLLER,
    GET_TICKET_FROM_JIRA,
    GET_VERSION_FROM_JIRA,
    COMPUTE_CHANGES_METRICS,
    COMPUTE_COMPLEXITY_METRICS,
    ENTRY_POINT_CONTROLLER,
    PROPORTION,
    CODE_SMELL_ANALYZER,
    LABELING,
    JAVA_METRIC_PARSER
}
