package org.isw2.factory;

public enum ControllerType {
    MAP_COMMITS_AND_METHODS,
    MERGE_VERSION_AND_COMMIT,
    GET_COMMIT_FROM_GIT,
    GET_FILE_DIFF_BETWEEN_COMMITS,
    GIT_CONTROLLER,
    GET_TICKET_FROM_JIRA,
    GET_VERSION_FROM_JIRA,
    COMPUTER_CHANGES_METRICS,
    COMPUTER_COMPLEXITY_METRICS,
    ENTRY_POINT_CONTROLLER,
    PROPORTION
}
